kind: pipeline
name: default

steps:
- name: docker-latest
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    repo: gomods/drone-helm
    tags:
      - latest
  when:
    branch:
      - main
    event:
      - push
