name: Shellcheck
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  shellcheck:
    name: Shellcheck push-helm-charts.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start check
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"